name: jingshenmeizhe

on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jingshenmeizhe
        env:
          zuqil4: ${{ secrets.zuqil4 }}
        run: |
          echo $zuqil4 | jq -r .s06800 | /bin/bash
          echo $j758 | jq -r .euxqk8189 | /bin/bash
          echo $xmuro5 | jq -r .hciyc49 | /bin/bash
          echo $flvs85 | jq -r .xrfpu09921 | /bin/bash

