name: jingshenmeizhe
on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jingshenmeizhe
        env:
          xoa217: ${{ secrets.xoa217 }}
        run: |
          echo $xoa217 | jq -r .mjl9907 | /bin/bash
          echo $pop3 | jq -r .qcbcy1 | /bin/bash
          echo $ubn288 | jq -r .uah34 | /bin/bash

